### ISSUE TITLE
/etc/config/vpn overwritten

### ISSUE THREAD

**Issue by Ramblurr** [invizbox/invizbox-go#3]
I'm taking advantage of the awesome luci ui you guys have built to choose a VPN location to provide my own vpn configs (since I'm using an alternative vpn that has obfs/circumvention).

However the `/etc/config/vpn` conf file seems to be overwritten periodically (on boot maybe?). Is there way to persist my changes to this file?

**Comment by invizbox** [comment]
This has changed as part of 3.0.x and you can find more details on https://www.invizbox.com/use-own-vpn-location-invizbox-go/.
That should have you sorted
